/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalyCalendar {
    /**
    * (optional) Locale
    */
    'locale': string;
    /**
    * (required) Month (1-12)
    */
    'month': number;
    /**
    * (optional) Number of months rendered
    */
    'numberOfMonths': number;
    /**
    * (optional) Range
    */
    'range': boolean;
    /**
    * (optional) Range end (dd-mm-yyyy)
    */
    'rangeEnd': string;
    /**
    * (optional) Range start (dd-mm-yyyy)
    */
    'rangeStart': string;
    /**
    * (optional) Selected day (dd-mm-yyyy)
    */
    'selected': string;
    /**
    * (optional) Start of the week. 0 for Sunday, 1 for Monday, etc.
    */
    'startOfTheWeek': number;
    /**
    * (required) Year (YYYY)
    */
    'year': number;
  }
}

declare global {


  interface HTMLCalyCalendarElement extends Components.CalyCalendar, HTMLStencilElement {}
  var HTMLCalyCalendarElement: {
    prototype: HTMLCalyCalendarElement;
    new (): HTMLCalyCalendarElement;
  };
  interface HTMLElementTagNameMap {
    'caly-calendar': HTMLCalyCalendarElement;
  }
}

declare namespace LocalJSX {
  interface CalyCalendar {
    /**
    * (optional) Locale
    */
    'locale'?: string;
    /**
    * (required) Month (1-12)
    */
    'month': number;
    /**
    * (optional) Number of months rendered
    */
    'numberOfMonths'?: number;
    /**
    * (optional) Event to listen for when new day is selected.
    */
    'onDaySelected'?: (event: CustomEvent<any>) => void;
    /**
    * (optional) Event to listen for when range end day is selected.
    */
    'onRangeEndSelected'?: (event: CustomEvent<any>) => void;
    /**
    * (optional) Event to listen for when range start day is selected.
    */
    'onRangeStartSelected'?: (event: CustomEvent<any>) => void;
    /**
    * (optional) Range
    */
    'range'?: boolean;
    /**
    * (optional) Range end (dd-mm-yyyy)
    */
    'rangeEnd'?: string;
    /**
    * (optional) Range start (dd-mm-yyyy)
    */
    'rangeStart'?: string;
    /**
    * (optional) Selected day (dd-mm-yyyy)
    */
    'selected'?: string;
    /**
    * (optional) Start of the week. 0 for Sunday, 1 for Monday, etc.
    */
    'startOfTheWeek'?: number;
    /**
    * (required) Year (YYYY)
    */
    'year': number;
  }

  interface IntrinsicElements {
    'caly-calendar': CalyCalendar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'caly-calendar': LocalJSX.CalyCalendar & JSXBase.HTMLAttributes<HTMLCalyCalendarElement>;
    }
  }
}


