/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyCalendar {
    'locale': string;
    'month': number;
    'selected': string;
    'startOfTheWeek': number;
    'year': number;
  }
}

declare global {


  interface HTMLMyCalendarElement extends Components.MyCalendar, HTMLStencilElement {}
  var HTMLMyCalendarElement: {
    prototype: HTMLMyCalendarElement;
    new (): HTMLMyCalendarElement;
  };
  interface HTMLElementTagNameMap {
    'my-calendar': HTMLMyCalendarElement;
  }
}

declare namespace LocalJSX {
  interface MyCalendar {
    'locale'?: string;
    'month'?: number;
    'onDaySelected'?: (event: CustomEvent<any>) => void;
    'selected'?: string;
    'startOfTheWeek'?: number;
    'year'?: number;
  }

  interface IntrinsicElements {
    'my-calendar': MyCalendar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-calendar': LocalJSX.MyCalendar & JSXBase.HTMLAttributes<HTMLMyCalendarElement>;
    }
  }
}


